### ISSUE TITLE
Backend:  Add "is_public" to a Coop's address field

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#37]
Currently, our Coop entities are associated with one or multiple addresses like so (from web/directory/models.py)...

```
class Coop(models.Model):
    objects = CoopManager()
    ...
    
    addresses = models.ManyToManyField(Address)
```
    
The "Address" model is from an open source module, django-addresses -- https://pypi.org/project/django-address/ .  The above relationship corresponds to the "directory_coop_addresses" table in the database.

We need to add an "is_public" boolean column to each directory's address (should default to true for public).  To be honest, not sure the best way to do this.  We might need to create a new Django model that represents the relationship between a Coop and an Address.  Open to other suggestions.

**Comment by nick-hou** [comment]
Hey @laredotornado, I'll take this one and #36 since they're pretty intertwined with #18, and I can just run the migration once.

**Comment by laredotornado** [comment]
Sounds good.  Adding "is_public" to address might be a little tricky since
the "address" functionality comes from a third party but if you see a path
forward there, I say have at it! -

**Comment by nick-hou** [comment]
Hey @laredotornado, been having some trouble running the DB migration on this one and might need your help. I think I've got the code all figured out on [my branch](https://github.com/nick-hou/maps/tree/info-is-public)

I created a new class "CoopAddressTags", and modified Coop.addresses to use the new class as a "through" class. This allows us to add any properties to a CoopAddressTags object to modify the coop-address relationship, i.e. an isPublic boolean. 

When running the migration, I get an error that I can't add "through" to an existing relationship: "Cannot alter field directory.Coop.addresses into directory.Coop.addresses - they are not compatible types (you cannot alter to or from M2M fields, or add or remove through= on M2M fields)." Sounds like this will require a rebuild rather than just a migration, which is definitely beyond my abilities.

**Comment by nick-hou** [comment]
Also something to consider - if our only goal really is to label addresses as public, we can just add an array of isPublic booleans to the Coop model and check it on the front-end. 

The through modifier makes it easier to add additional properties to each address, essentially functioning as tags. Not really sure what kind of info we could add to individual addresses that isn't covered by the other Coop fields, but if that seems useful then it'll be worth going through the DB rebuild.

**Comment by laredotornado** [comment]
I think the through approach is the way to go here.  I'm not sure offhand
why this error occurs.  Let me do some initial research and then if I can't
find anything, maybe we can do a screen share to troubleshoot some other
paths around it (like the one you mentioned).

**Comment by laredotornado** [comment]
Hi @nick-hou , I checked out your fork but couldn't reproduce your issue.  DId you check in the db migration you created?  I get this when I try and create or run migrations ...

```
(venv) $ python manage.py migrate
Operations to perform:
  Apply all migrations: address, auth, contenttypes, directory, sessions
Running migrations:
  No migrations to apply.

(venv) $ python manage.py makemigrations
No changes detected
```
