### ISSUE TITLE
Frontend: Expand advanced search to include zip, city, address, and coop type

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#57]
We would like to expand the search form at

https://prod.chicommons.coop/advanced

to include the following fields.  

| Field               | Input Type     | JSON Form Name|
| ------------- | ------------- | ----------------- |
| Zip                 | Text Field      | zip                        |
| City                | Text Field       | city                      |
| Address         | Text Field       | street                   |
| Coop Type     | Select menu  | coop_type           |

The items in the drop down menu for "Coop Type" will come from this endpoint -- /coop_types .  The data will look like below

```
[ 
    {"id": 123, "name": "Community Garden"},
   {"id": 234, "name": "Credit Union"},
   ...
]
```

**Comment by ozzysChiefDataScientist** [comment]
@laredotornado Can you assign this issue to me? 
Some questions:
1) Should I sort the Coop Types in alpha order?
2) I noticed that some Coop Types are lower case, but other are camel case. Should I standardize all coop types to display in camel case in the dropdown menu?[
<img width="397" alt="coop_tyes" src="https://user-images.githubusercontent.com/42755977/116330618-864a9d00-a793-11eb-8393-d4334008821a.png">
](url)
3) Has the backend been updated so that search results will filter based on provided address, city, zip, and coop type parameters? When I searched on "http://localhost:9090/coops/?city=Evanston," the results did not appear filterered -- I think it's pulling records from all cities.
<img width="342" alt="evanston-search" src="https://user-images.githubusercontent.com/42755977/116330835-f8bb7d00-a793-11eb-9497-7237a0a97cc3.png">
Thank you!

**Comment by laredotornado** [comment]
Hi there, 1. Yes, please sort case-insensitively.  2. No need to standardize -- this data comes from the backend so I feel like that's where the data should be corrected.  3.  You're too fast!  I haven't updated the backend yet to include the new search fields.  Hope to have that done by end of week.

Thanks so much! -

**Comment by laredotornado** [comment]
@ozzysChiefDataScientist , please update to the latest, I have added support on the backend for the three additional search fields.  Thanks, -

**Comment by ozzysChiefDataScientist** [comment]
@laredotornado Thanks! I will check this out.

**Comment by ozzysChiefDataScientist** [comment]
Hi @laredotornado  -- Thank you. I tested the city, street, and zip searches and these are all working. 

I'm having trouble with the coop_type search though. When I search on "http://localhost:9090/coops/?coop_type=Community%20Garden," it looks like all coops are returned, not just community gardens. I noticed that the [recent commit](https://github.com/chicommons/maps/commit/d979054db747c5dde6b0386cecf19755581ca62c) on web/directory/views.py doesn't appear to have the coop_type on the get request -- could that be why? 

I also noticed on your [unit test](https://github.com/chicommons/maps/blob/d979054db747c5dde6b0386cecf19755581ca62c/web/scripts/test_get_coop_by_mult_criteria.sh) that you wrote "coop_type=Community+Garden." Should I use a "+" to encode spaces in the coop type search URL? My current code puts a "%20" to encode spaces. Just want to make sure I'm following your preference or requirement.

**Comment by laredotornado** [comment]
Oops!  Good catch.  Just checked in something to add support for
coop_type.  You can use either a "+" or "%20" to encode for the space, most
likely whatever library you use to encode query params will do it correctly
so you shouldn't have to do anything special, but to answer your question,
either will work.
